services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/teleclinic
      - NODE_ENV=development
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: apps/frontend/Dockerfile
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teleclinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 