name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      ALLOWED_ORIGINS: http://localhost
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build frontend image
        run: docker build -f apps/frontend/Dockerfile .
      - name: Build backend image
        run: docker build -f apps/backend/Dockerfile .

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      # Deployment steps will be added later
      # Environment variables will be added later 