name: Sync Backend to Deployment Repo

on:
  push:
    branches: [main]
    paths:
      - 'apps/backend/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: monorepo

      - uses: actions/checkout@v3
        with:
          repository: mattburnett-repo/teleclinic-api
          path: deploy-repo
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Sync Files
        run: |
          # Clean deployment repo
          cd deploy-repo
          find . -not -path './.git/*' -not -name '.git' -delete

          # Copy backend files
          cp -r ../monorepo/apps/backend/* ./

          # Create simple Dockerfile
          cat << 'EOF' > Dockerfile
          FROM node:18

          WORKDIR /app

          COPY package.json ./
          RUN npm install --legacy-peer-deps

          COPY . .
          RUN npm run build

          EXPOSE 3000
          CMD ["npm", "run", "start:prod"]
          EOF

          # Commit and push
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync from monorepo" && git push) 