name: Sync Frontend to Deployment Repo

on:
  push:
    branches: [main]
    paths:
      - 'apps/frontend/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: monorepo

      - uses: actions/checkout@v3
        with:
          repository: mattburnett-repo/teleclinic-client
          path: deploy-repo
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Sync Files
        run: |
          # Clean deployment repo
          cd deploy-repo
          find . -not -path './.git/*' -not -name '.git' -delete

          # Copy all frontend files
          cp -r ../monorepo/apps/frontend/* ./

          # Add missing types to package.json
          npm install --save-dev @types/react @types/react-dom @types/jest

          # Commit and push
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync from monorepo" && git push) 